language: node_js
node_js:
  - stable

script:
  # build library and prepare demo application
  - npm run build
  # set the base href
  - BASE='/'$(echo "${TRAVIS_REPO_SLUG}" | sed 's/^.*\/\(.*\)$/\1/')'/'
  - npm run ng config projects.demo.architect.build.options.baseHref "'${BASE}'"
  - npm run ng config projects.demo.architect.build.options.deployUrl "'${BASE}'"
  # buid the demo application
  - cd .temp && npm run build -- --prod --progress=false
  # copy the built folder to target
  - mkdir -p ../gh-pages && mv dist/demo/* ../gh-pages

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: gh-pages
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
