language: node_js
node_js:
  - stable

script:
  # build library and prepare demo application
  - npm run build
  # buid the demo application
  - cd .temp && npm run build --prod --base-href=/ngx-grid/
  # copy the built folder to target
  - mv dist/* ../gh-pages

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: gh-pages
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
