language: node_js
node_js:
  - stable

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: demo
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
